-- Ya estamos en la base de datos pruebaDb

-- Crear esquema dbo si no existe
CREATE SCHEMA IF NOT EXISTS dbo;

-- Crear tabla de productos
CREATE TABLE IF NOT EXISTS dbo.productos (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY
(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    actualizado_en TIMESTAMP(6),
    categoria VARCHAR(50),
    creado_en TIMESTAMP(6),
    descripcion VARCHAR(255),
    nombre VARCHAR(100) NOT NULL,
    precio NUMERIC(10, 2) NOT NULL,
    CONSTRAINT productos_pkey PRIMARY KEY (id)
    );

-- Insertar productos de ejemplo
INSERT INTO dbo.productos (actualizado_en, categoria, creado_en, descripcion, nombre, precio) VALUES
                                                                                                  (NOW(), 'Tecnología', NOW(), 'Laptop HP Pavilion 15 pulgadas', 'Laptop HP', 799.99),
                                                                                                  (NOW(), 'Tecnología', NOW(), 'Monitor Dell 27 pulgadas 4K', 'Monitor Dell', 349.99),
                                                                                                  (NOW(), 'Tecnología', NOW(), 'Teclado mecánico RGB', 'Teclado Logitech', 59.99);

-- Crear tabla de inventario
CREATE TABLE IF NOT EXISTS dbo.inventarios (
                                               producto_id BIGINT NOT NULL,
                                               cantidad_disponible INTEGER NOT NULL,
                                               ultima_actualizacion TIMESTAMP(6) NOT NULL,
    CONSTRAINT inventarios_pkey PRIMARY KEY (producto_id)
    );

-- Insertar inventario correspondiente a cada producto
INSERT INTO dbo.inventarios (producto_id, cantidad_disponible, ultima_actualizacion) VALUES
                                                                                         (1, 15, NOW()),
                                                                                         (2, 27, NOW()),
                                                                                         (3, 42, NOW());
